sudo: false
notifications:
  email: false
branches:
  only:
    - master

language: node_js
node_js:
   - "11.2.0"
cache:
  directories:
    - "node_modules"

before_script:
  - npm prune
script:
  - npm run lint
  - npm run test:ci
  - npm run test:coverage
after_success:
  - echo "$TRAVIS_BRANCH"
  - npm run report-coverage
